---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.18.6

platforms:
- name: windows-2012-standard
  driver:
    guest: :windows
    gui: true
    box: chef/windows-server-2012r2-standard
    username: vagrant
    password: vagrant
    port: 5985
    customize:
      memory: '2048'
      cpus: '2'
      vram: '32'
      natdnsproxy1: 'off'
      natdnshostresolver1: 'off'
  transport: 
      name: winrm 
      max_threads: 4

suites:
- name: handlers
  run_list: ["recipe[summary_handlers]"]
  attributes: 